### ISSUE TITLE
7.1未适配

### ISSUE THREAD

**Issue by ruanbaojun1105** [yanzhenjie/Album#105]
直接报错

**Comment by kangdawei** [comment]
修改：
AlbumNullFragment
里面
mStatusView = (NavigationView) view.findViewById(R.id.status_view);
就可以了

**Comment by yanzhenjie** [comment]
@ruanbaojun1105 能否提供一下堆栈信息，确定问题后我会立刻发布新版。

**Comment by ruanbaojun1105** [comment]
android.os.FileUriExposedException: file:///storage/emulated/0/... exposed beyond app through Intent.getData()
    at android.os.StrictMode.onFileUriExposed(StrictMode.java:1816)
    at android.net.Uri.checkFileUriExposed(Uri.java:2350)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:9076)
    at android.content.Intent.prepareToLeaveProcess(Intent.java:9037)
    at android.app.Instrumentation.execStartActivity(Instrumentation.java:1530)
    at android.app.Activity.startActivityForResult(Activity.java:4391)
    at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivity.java)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java)
    at android.app.Activity.startActivityForResult(Activity.java:4335)
    at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java)
    at android.app.Activity.startActivity(Activity.java:4697)
    at android.app.Activity.startActivity(Activity.java:4665)
    at com.ijuyin.prints.news.utils.VersionUtils$1.handleMessage(VersionUtils.java)
    at android.os.Handler.dispatchMessage(Handler.java:105)
    at android.os.Looper.loop(Looper.java:156)
    at android.app.ActivityThread.main(ActivityThread.java:6524)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

**Comment by ruanbaojun1105** [comment]
在有些7.0以上的手机，能打开相机 ，拍完照后图片无法显示，获取的 图片也只能显示一部分，很多图片也不能显示，在一加3T上，图片用glide显示不修改宽高能显示 ，修改宽高后无法显示，摸不着头脑

**Comment by yanzhenjie** [comment]
@ruanbaojun1105 你用是哪个版本，7.0很早就适配了，我刚才特意测试了7.0手机和模拟器，测试了Album的所有功能，均不存在uri的问题，Album的版本是2.0.1。  
图片显示的问题应该和Album无关，Album只是把图片路径给你。

**Comment by yanzhenjie** [comment]
刚刚发布了新版本2.0.2，解决了现在大家提的一些bug和不完善的逻辑，同时更新了support库为26.1.0，大家更新新版本试试看。
