### ISSUE TITLE
拍照之后，再继续拍照会出错，忘解决

### ISSUE THREAD

**Issue by MoMyles** [yanzhenjie/Album#114]
Caused by: java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:583)
at android.os.AsyncTask.execute(AsyncTask.java:539)
at com.yanzhenjie.album.ui.AlbumFragment$6.onAction(AlbumFragment.java:428)
at com.yanzhenjie.album.ui.AlbumFragment$6.onAction(AlbumFragment.java:416)
at com.yanzhenjie.album.ui.CameraActivity.onCameraResult(CameraActivity.java:258)
at com.yanzhenjie.album.ui.CameraActivity.onActivityResult(CameraActivity.java:243)
at android.app.Activity.dispatchActivityResult(Activity.java:6192)
at android.app.ActivityThread.deliverResults(ActivityThread.java:3570)
at android.app.ActivityThread.handleSendResult(ActivityThread.java:3617) 
at android.app.ActivityThread.access$1300(ActivityThread.java:151) 
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1352) 
at android.os.Handler.dispatchMessage(Handler.java:102) 
at android.os.Looper.loop(Looper.java:135) 
at android.app.ActivityThread.main(ActivityThread.java:5254) 
at java.lang.reflect.Method.invoke(Native Method) 
at java.lang.reflect.Method.invoke(Method.java:372) 
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by liuyaxing** [comment]
我试了试 。注释掉AlbumFragment的425行  if (mConvertTask == null)  可以正常拍照    不知道会不会影响其他东西

**Comment by yanzhenjie** [comment]
已经发布新版本了，大概10分钟后更新到github。
