### ISSUE TITLE
拍摄视频后返回报错

### ISSUE THREAD

**Issue by ruanbaojun1105** [yanzhenjie/Album#118]
.album.camera.provider/external_files/Movies/20171109_110305672_9f0f790fd646fb2bbabf5ba5dc52bebd.mp4 flg=0x1 launchParam=MultiScreenLaunchParams { mDisplayId=0 mFlags=0 } (has extras) }} to activity {com.hwx.balancingcar.balancingcar/com.yanzhenjie.album.ui.CameraActivity}: java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4447)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4490)
                                                                                       at android.app.ActivityThread.-wrap22(ActivityThread.java)
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684)
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                       at android.os.Looper.loop(Looper.java:154)
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6646)
                                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
                                                                                    Caused by: java.lang.IllegalStateException: Cannot execute task: the task has already been executed (a task can be executed only once)
                                                                                       at android.os.AsyncTask.executeOnExecutor(AsyncTask.java:605)
                                                                                       at android.os.AsyncTask.execute(AsyncTask.java:560)
                                                                                       at com.yanzhenjie.album.ui.AlbumFragment$6.onAction(AlbumFragment.java:428)
                                                                                       at com.yanzhenjie.album.ui.AlbumFragment$6.onAction(AlbumFragment.java:416)
                                                                                       at com.yanzhenjie.album.ui.CameraActivity.onCameraResult(CameraActivity.java:258)
                                                                                       at com.yanzhenjie.album.ui.CameraActivity.onActivityResult(CameraActivity.java:243)
                                                                                       at android.app.Activity.dispatchActivityResult(Activity.java:7226)
                                                                                       at android.app.ActivityThread.deliverResults(ActivityThread.java:4443)
                                                                                       at android.app.ActivityThread.handleSendResult(ActivityThread.java:4490) 
                                                                                       at android.app.ActivityThread.-wrap22(ActivityThread.java) 
                                                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1684) 
                                                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                       at android.os.Looper.loop(Looper.java:154) 
                                                                                       at android.app.ActivityThread.main(ActivityThread.java:6646) 
                                                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468) 
                                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)

**Comment by yanzhenjie** [comment]
已经发布新版本了，10分钟后更新到github。

**Comment by ruanbaojun1105** [comment]
谢了，设置了视频时长过滤，开启录制视频完成后，超过过滤时长会报错，我再试试

**Comment by yanzhenjie** [comment]
嗯，2.0.1会出现只要连续调用了2次相机就会出现这个问题，是`Asynctask`使用上的bug，新版本已经修复了。
