### ISSUE TITLE
收集到一个崩溃信息

### ISSUE THREAD

**Issue by FashionZhang** [yanzhenjie/Album#163]
java.lang.RuntimeException: Unable to start activity ComponentInfo{此处省略/com.yanzhenjie.album.ui.AlbumActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yanzhenjie.album.api.widget.Widget.getNavigationBarColor()' on a null object reference
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2479)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2539)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yanzhenjie.album.api.widget.Widget.getNavigationBarColor()' on a null object reference
	at com.yanzhenjie.album.ui.AlbumActivity.initializeWidget(AlbumActivity.java:108)
	at com.yanzhenjie.album.ui.AlbumActivity.onCreate(AlbumActivity.java:84)
	at android.app.Activity.performCreate(Activity.java:6372)
	at `android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1110)`
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2432)
	... 9 more

` Album.image(context)
                    .multipleChoice()
                    .requestCode(REQUEST_SELECT_IMAGE)
                    .columnCount(4)
                    .selectCount(mFieldList.get(mPosition).getCount() - imageData.previewImages.size())
                    .camera(true)
                    .widget(
                            Widget.newDarkBuilder(context)
                                    .title(mFieldList.get(mPosition).getName())
                                    .build()
                    )`

**Comment by FashionZhang** [comment]
机型 huawei MLA-AL0
