### ISSUE TITLE
建议、功能优化收集，如果是bug请单独发起Issue

### ISSUE THREAD

**Issue by yanzhenjie** [yanzhenjie/Album#17]
这是一个功能优化收集issue，如果是bug，请单独发起一个issue。  
主要收集但不仅限于以下几类问题：  
1. 还需要什么你想要的新功能Album没有的。  
2. 哪个功能不是很完善，比如加载图片过慢，长图大图不是很清晰。  
3. 哪个功能逻辑需要改动，比如提供单独调用相机的功能。

当然不仅限于以上问题，如果你有其它想法欢迎提出。  

我更鼓励有问题自己解决，如果发现bug或者其它优化，是你力所能及的，我更加欢迎你提交PR。  

> 注：请不要关闭这个issue，这个issue是常开状态，希望集大家的力量把Album做到更优。

**Comment by unborn2016** [comment]
拍照后的图片裁剪，或者相册自选一张照片后的裁剪，适用场景 头像的选择编辑。

**Comment by siriusyang** [comment]
7.0适配了吗

**Comment by yanzhenjie** [comment]
@siriusyang 已经兼容。

**Comment by zhangchunbin** [comment]
图片预览的时候，点击图片的时候能不能隐藏掉标题栏和下面的选择栏，就是沉浸式效果。如果能修改成这样的那就更完美了

**Comment by zhangchunbin** [comment]
图片加载库即使用到了picasso，又使用到了glide，这个能不能只使用一个呢？如果这个能简化的话，那就更完美了，期待作者的回复。

**Comment by douya40** [comment]
优化建议，选择图片返回的时候可以自定义压缩比例，返回图片的显示方式可以自定义显示格式，比如单行显示，九宫格显示。可以对选择完的图片进行编辑比如图片位置的长按移动位置，删除图片等等。

**Comment by yanzhenjie** [comment]
@douya40 你好，你描述的几点中，只有压缩比例这个可以优化。  

1. 返回图片的显示格式，和Album无关，完全是你自己控制的，包括页面，你看到的只是demo中提供，当然README的图片中有九宫格和丝攻个的。  
2. 由于1，所以用户选择的图片也存在编辑问题了，如果你想自己实现图片的拖拽，你可以使用[SwipeRecyclerView](https://github.com/yanzhenjie/SwipeRecyclerView)。

谢谢反馈。

**Comment by douya40** [comment]
主要是图片返回的编辑上传也是个模块

**Comment by yanzhenjie** [comment]
@douya40 图片编辑上传具体是什么意思？涂鸦还是Item的拖拽？上传是否是要上传到Http服务器？这些跟相册都没关系呀。  
文件上传你可以使用[NoHttp](https://github.com/yanzhenjie/NoHttp)

**Comment by HeyManImMoy** [comment]
建议选中的图片蒙上一层半透明黑色蒙版，因为有些图片颜色和checkbox颜色很接近，根本看不出已经选择了那一张。（还有就是当maxsize为1时，添加裁剪功能。）

**Comment by douya40** [comment]
https://github.com/bingoogolapple/BGAPhotoPicker-Android  参考一下

**Comment by tengfangjiang** [comment]
代码好像未上传完整com.yanzhenjie.fragment.CompatActivity、com.yanzhenjie.fragment.NoFragment、com.yanzhenjie.mediascanner.MediaScanner、com.yanzhenjie.alertdialog.AlertDialog、com.yanzhenjie.album.widget.recyclerview.AlbumVerticalGirdDecoration

**Comment by SuzutsukiKagami** [comment]
可不可以设置拍照后是否同时备份在本地相机？

**Comment by yanzhenjie** [comment]
谢谢大家反馈，统一回复。
@HeyManImMoy  蒙板这个建议很好，在下个版本添加。
@tengfangjiang  代码我检查过了，代码是全的。
@SuzutsukiKagami  你是说扫描到多媒体库吗？这个暂时不能配置，下下个版本会添加。

统一回复图片剪切问题，因为相册和图片剪切功能相关性不大，因为很多人只需要选择，很多人只需要剪切，所以我会单独开一个库来做剪切，预计下周会发布。

**Comment by sungentim** [comment]
版本：1.0.2
异常:Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
	at com.yanzhenjie.album.fragment.AlbumFragment.showImageFromFolder(AlbumFragment.java:205)
	at com.yanzhenjie.album.fragment.AlbumFragment.onResume(AlbumFragment.java:161)
	at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
	at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
	at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
	at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
	at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
	at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
	at android.app.Activity.performResume(Activity.java:6255)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3265)
	... 12 more

**Comment by sungentim** [comment]
说明:我的targetSdkVersion 是22,出现问题的手机都是小米手机（MI 4LTE ，Redmi 4,Redmi 4note 4x）
版本：1.0.2
异常：java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=21215, uid=10032 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:493)
	at android.content.ContentResolver.query(ContentResolver.java:435)
	at android.provider.MediaStore$Images$Media.query(MediaStore.java:841)
	at com.yanzhenjie.album.task.ScanTask.getPhotoAlbum(ScanTask.java:112)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:88)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more

**Comment by yanzhenjie** [comment]
@sungentim bug请单独发issue，你的这个我删除了。另外请使用最新版本，你已经落后好几个版本了。

**Comment by HeyManImMoy** [comment]
@yanzhenjie 请问蒙板功能加上去了吗？

**Comment by Cashdispenser** [comment]
单独调用相册的功能，不需要相机

**Comment by yanzhenjie** [comment]
@Cashdispenser 亲，你提的这个功能，本身就支持的，使用相册时候可以禁用相机的：
```java
Album.album(this)
    .camera(false)
    ...
```

**Comment by Cashdispenser** [comment]
@yanzhenjie 我的锅  没仔细看使用教程   谢了

**Comment by Cashdispenser** [comment]
希望能做成有相册有摄像头模式下，拍完照后直接返回，不用再回到相册的界面

**Comment by yanzhenjie** [comment]
@Cashdispenser 那是不对的，你可以单独使用Album的相机。

**Comment by yanzhenjie** [comment]
这个issue和我当初的计划有点相悖了，以后大家任何问题还是单独提issue吧，这个issue关闭了，感谢大家的反馈。
