### ISSUE TITLE
MediaReadTask空指针问题

### ISSUE THREAD

**Issue by mycold** [yanzhenjie/Album#189]
手机： 魅蓝max
这是报空指针的代码：
        //格式限制 在 jpeg  png   mp4
        mMimeFilter = new Filter<String>() {

            @Override
            public boolean filter(String attributes) {
                return !(attributes.contains("jpeg") || attributes.contains("png") || attributes.contains("mp4"));
            }
        };

启动MediaReadTask之后就报这个attributes.contains()空指针错误，别的没什么操作了

报错日志：
java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:318)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at com.art.activity.MyAlbumActivity$3.a(MyAlbumActivity.java:148)
	at com.art.activity.MyAlbumActivity$3.filter(MyAlbumActivity.java:144)
	at com.yanzhenjie.album.task.MediaReader.scanImageFile(MediaReader.java:142)
	at com.yanzhenjie.album.task.MediaReader.getAllMedia(MediaReader.java:311)
	at com.yanzhenjie.album.task.MediaReadTask.doInBackground(MediaReadTask.java:102)
	at com.yanzhenjie.album.task.MediaReadTask.doInBackground(MediaReadTask.java:35)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.contains(java.lang.CharSequence)' on a null object reference
	at com.art.activity.MyAlbumActivity$3.a(MyAlbumActivity.java:148)
	at com.art.activity.MyAlbumActivity$3.filter(MyAlbumActivity.java:144)
	at com.yanzhenjie.album.task.MediaReader.scanImageFile(MediaReader.java:142)
	at com.yanzhenjie.album.task.MediaReader.getAllMedia(MediaReader.java:311)
	at com.yanzhenjie.album.task.MediaReadTask.doInBackground(MediaReadTask.java:102)
	at com.yanzhenjie.album.task.MediaReadTask.doInBackground(MediaReadTask.java:35)
	at android.os.AsyncTask$2.call(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:243)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:761)

**Comment by yanzhenjie** [comment]
哪个版本？你可以可以做个判空。

**Comment by mycold** [comment]
2.0.2版本

**Comment by yanzhenjie** [comment]
版本差距有点大，你可以升级一下。

**Comment by mycold** [comment]
更新之后部分资源文件和类文件缺失
