### ISSUE TITLE
2.1.2 多图模式下缩放崩溃

### ISSUE THREAD

**Issue by xiang23** [yanzhenjie/Album#197]
信息如下:UncaughtException detected: java.lang.IllegalArgumentException: pointerIndex out of range
        at android.view.MotionEvent.nativeGetAxisValue(Native Method)
        at android.view.MotionEvent.getX(MotionEvent.java:2372)
        at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2402)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2865)
        at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:2550)
        at com.android.internal.policy.DecorView.superDispatchTouchEvent(DecorView.java:509)
        at com.android.internal.policy.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1863)
        at android.app.Activity.dispatchTouchEvent(Activity.java:3226)
        at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
        at com.android.internal.policy.DecorView.dispatchTouchEvent(DecorView.java:471)
        at android.view.View.dispatchPointerEvent(View.java:10960)
        at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:5068)
        at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4920)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
        at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:4603)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
        at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:4660)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
        at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:4504)
        at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:4470)
        at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:4478)
        at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:4451)
        at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:6953)
        at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:6892)
        at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:6853)
        at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:7063)
        at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
        at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
        at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
        at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:7027)
        at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:7090)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
        at android.view.Choreographer.doCallbacks(Choreographer.java:702)
        at android.view.Choreographer.doFrame(Choreographer.java:632)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6646)
        at java.lang.reflect.Method.invoke(Native Method)
    	at com.android.in

**Comment by gyb3320** [comment]
同问+1

**Comment by vjs987** [comment]
Happened to me as well. Please fix :)

**Comment by vjs987** [comment]
This happens while pinching to zoom (multiple times) on an image loaded via the gallery.

**Comment by jiao08** [comment]
在ViewPager里缩放图片过小出的异常
java.lang.IllegalArgumentException: pointerIndex out of range - CSDN博客  https://blog.csdn.net/ganhualin/article/details/38397253
希望参考下上面的做法改掉这个bug.
