### ISSUE TITLE
android7.0手机调用相机会崩溃

### ISSUE THREAD

**Issue by Zorphling** [yanzhenjie/Album#21]
android.os.FileUriExposedException: file:///storage/emulated/0/DCIM/20170405_184128485.jpg exposed beyond app through ClipData.Item.getUri()
                                                                           at android.os.StrictMode.onFileUriExposed(StrictMode.java:1799)
                                                                           at android.net.Uri.checkFileUriExposed(Uri.java:2346)
                                                                           at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                           at android.content.Intent.prepareToLeaveProcess(Intent.java:8923)
                                                                           at android.content.Intent.prepareToLeaveProcess(Intent.java:8908)
                                                                           at android.app.Instrumentation.execStartActivity(Instrumentation.java:1519)
                                                                           at android.app.Activity.startActivityForResult(Activity.java:4288)
                                                                           at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                           at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                           at android.support.v4.app.ActivityCompatJB.startActivityForResult(ActivityCompatJB.java:30)
                                                                           at android.support.v4.app.ActivityCompat.startActivityForResult(ActivityCompat.java:146)
                                                                           at android.support.v4.app.FragmentActivity.startActivityFromFragment(FragmentActivity.java:937)
                                                                           at android.support.v4.app.FragmentActivity$HostCallbacks.onStartActivityFromFragment(FragmentActivity.java:1047)
                                                                           at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:959)
                                                                           at android.support.v4.app.Fragment.startActivityForResult(Fragment.java:948)
                                                                           at com.yanzhenjie.album.util.AlbumUtils.startCamera(AlbumUtils.java:39)
                                                                           at com.yanzhenjie.album.fragment.BasicCameraFragment.cameraWithPermission(BasicCameraFragment.java:106)
                                                                           at com.yanzhenjie.album.fragment.BasicCameraFragment.cameraUnKnowPermission(BasicCameraFragment.java:61)
                                                                           at com.yanzhenjie.album.fragment.AlbumFragment$3.onItemClick(AlbumFragment.java:220)
                                                                           at com.yanzhenjie.album.adapter.AlbumImageAdapter$ItemViewHolder$1.onClick(AlbumImageAdapter.java:194)
                                                                           at android.view.View.performClick(View.java:5611)
                                                                           at android.view.View$PerformClick.run(View.java:22276)
                                                                           at android.os.Handler.handleCallback(Handler.java:751)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:154)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:6114)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by yanzhenjie** [comment]
1.0.2和1.0.3已经修复了，请升级最新版再看看，期待你的回复。

**Comment by Zorphling** [comment]
多谢,大神写的很好用
