### ISSUE TITLE
小米3S Android 6.0 报错

### ISSUE THREAD

**Issue by xjhh** [yanzhenjie/Album#223]
报错：android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?

**Comment by wuhenzhizao** [comment]
我也出现了，android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
                                                       at android.app.ContextImpl.startActivity(ContextImpl.java:760)
                                                       at android.app.ContextImpl.startActivity(ContextImpl.java:740)
                                                       at android.content.ContextWrapper.startActivity(ContextWrapper.java:331)

**Comment by wuhenzhizao** [comment]
context传的可能是applicationContext

**Comment by nakharin** [comment]
from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
