### ISSUE TITLE
Orientation should not be the case

### ISSUE THREAD

**Issue by zeropercenthappy** [yanzhenjie/Album#230]
```
    java.lang.AssertionError: This should not be the case.
        at com.yanzhenjie.album.app.album.AlbumView.getOrientation(AlbumView.java:175)
        at com.yanzhenjie.album.app.album.AlbumView.setupViews(AlbumView.java:126)
        at com.yanzhenjie.album.app.album.AlbumActivity.onCreate(AlbumActivity.java:106)
        at android.app.Activity.performCreate(Activity.java:6357)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2436)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2543)
        at android.app.ActivityThread.access$1000(ActivityThread.java:156)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1407)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:157)
        at android.app.ActivityThread.main(ActivityThread.java:5653)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:746)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:636)
```

with ` MIUI 9.2 Android 6.0.1 Mi6 Note` and `MIUI 10 Android 8.0.0 Mi 6`

**Comment by zeropercenthappy** [comment]
Close. the reason of this problem is cause I've been modified Configuration in my BaseActivity.
