### ISSUE TITLE
禁止拍照权限后崩溃

### ISSUE THREAD

**Issue by keaideluren** [yanzhenjie/Album#232]
华为荣耀9, Android8.0.0，
 Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.huawei.camera/.ThirdCamera clip={text/uri-list U:content://{这里是包名}.file.provider/external_path/DCIM/20181114_154512670_5befa43eba4f64ba0ef00b1dfc8daba1.jpg} (has extras) } from ProcessRecord{d12b8e5 13557:com.uoko.ukpartnerapp/u0a521} (pid=13557, uid=10521) with revoked permission android.permission.CAMERA
        at android.os.Parcel.readException(Parcel.java:1946)
        at android.os.Parcel.readException(Parcel.java:1892)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4373)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1631)
        at android.app.Activity.startActivityForResult(Activity.java:4751)
        at android.support.v4.app.BaseFragmentActivityApi16.startActivityForResult(BaseFragmentActivityApi16.java:54)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:68)
        at android.app.Activity.startActivityForResult(Activity.java:4691)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:751)
        at com.yanzhenjie.album.util.AlbumUtils.takeImage(AlbumUtils.java:120)
        at com.yanzhenjie.album.app.camera.CameraActivity.onPermissionGranted(CameraActivity.java:117)
        at com.yanzhenjie.album.mvp.BaseActivity.onRequestPermissionsResult(BaseActivity.java:71)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7843)
        at android.app.Activity.dispatchActivityResult(Activity.java:7694)
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4928)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975) 
        at android.app.ActivityThread.-wrap20(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950) 
        at android.os.Handler.dispatchMessage(Handler.java:108) 
        at android.os.Looper.loop(Looper.java:166) 
        at android.app.ActivityThread.main(ActivityThread.java:7425) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)

**Comment by keaideluren** [comment]
忘了在manifest中注册了

**Comment by keaideluren** [comment]
还是会崩~~

**Comment by yanzhenjie** [comment]
This has been fixed in #229. I will send a new version.
