### ISSUE TITLE
图库的相机拍照请求相机权限异常

### ISSUE THREAD

**Issue by lizhanqi** [yanzhenjie/Album#237]
java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.suxuantech.erpsys/com.yanzhenjie.album.app.camera.CameraActivity}: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.huawei.camera/.ThirdCamera clip={text/uri-list U:content://com.suxuantech.erpsys.app.file.provider/external_path/DCIM/20181206_151246103_5a293a3a447091123f75fd965e5344c4.jpg} (has extras) } from ProcessRecord{6528698 22316:com.suxuantech.erpsys/u0a757} (pid=22316, uid=10757) with revoked permission android.permission.CAMERA
        at android.app.ActivityThread.deliverResults(ActivityThread.java:4932)
        at android.app.ActivityThread.handleSendResult(ActivityThread.java:4975)
        at android.app.ActivityThread.-wrap20(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1950)
        at android.os.Handler.dispatchMessage(Handler.java:108)
        at android.os.Looper.loop(Looper.java:166)
        at android.app.ActivityThread.main(ActivityThread.java:7425)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:245)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:921)
     Caused by: java.lang.SecurityException: Permission Denial: starting Intent { act=android.media.action.IMAGE_CAPTURE flg=0x3 cmp=com.huawei.camera/.ThirdCamera clip={text/uri-list U:content://com.suxuantech.erpsys.app.file.provider/external_path/DCIM/20181206_151246103_5a293a3a447091123f75fd965e5344c4.jpg} (has extras) } from ProcessRecord{6528698 22316:com.suxuantech.erpsys/u0a757} (pid=22316, uid=10757) with revoked permission android.permission.CAMERA
        at android.os.Parcel.readException(Parcel.java:1954)
        at android.os.Parcel.readException(Parcel.java:1900)
        at android.app.IActivityManager$Stub$Proxy.startActivity(IActivityManager.java:4373)
        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1631)
        at android.app.Activity.startActivityForResult(Activity.java:4751)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:767)
        at android.app.Activity.startActivityForResult(Activity.java:4691)
        at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:754)
        at com.yanzhenjie.album.util.AlbumUtils.takeImage(AlbumUtils.java:120)
        at com.yanzhenjie.album.app.camera.CameraActivity.onPermissionGranted(CameraActivity.java:117)
        at com.yanzhenjie.album.mvp.BaseActivity.onRequestPermissionsResult(BaseActivity.java:71)
        at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7843)
        at android.app.Activity.dispatchActivityResult(Activity.java:7694)

**Comment by yanzhenjie** [comment]
哪个版本？
