### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference

### ISSUE THREAD

**Issue by rakeshparveen5** [yanzhenjie/Album#263]
java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.ArrayList.size()' on a null object reference
	at com.yanzhenjie.album.app.album.AlbumActivity.clickCamera(AlbumActivity.java:252)
	at com.yanzhenjie.album.app.album.AlbumView$1.onItemClick(AlbumView.java:134)
	at com.yanzhenjie.album.app.album.AlbumAdapter$ButtonViewHolder.onClick(AlbumAdapter.java:180)
	at android.view.View.performClick(View.java:5637)
	at android.view.View$PerformClick.run(View.java:22433)
	at android.os.Handler.handleCallback(Handler.java:751)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6119)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

**Comment by liufei96** [comment]
问题解决了吗？

**Comment by rakeshparveen5** [comment]
not fixed yet

**Comment by sspogra** [comment]
Not fixed.
