### ISSUE TITLE
去选择图片 崩溃,以下为报错信息

### ISSUE THREAD

**Issue by liujiwei5018** [yanzhenjie/Album#274]
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/app/Contract$AlbumPresenter;
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36)
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26)
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190)
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179)
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48)
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22)
        at android.view.View.performClick(View.java:6614)
        at android.view.View.performClickInternal(View.java:6591)
        at android.view.View.access$3100(View.java:786)
        at android.view.View$PerformClick.run(View.java:25948)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:207)
        at android.app.ActivityThread.main(ActivityThread.java:6809)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876)
     Caused by: java.lang.ClassNotFoundException: com.yanzhenjie.album.app.Contract$AlbumPresenter
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36) 
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179) 
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/mvp/BasePresenter;
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36) 
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179) 
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
     Caused by: java.lang.ClassNotFoundException: com.yanzhenjie.album.mvp.BasePresenter
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36) 
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179) 
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleOwner;
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36) 
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179) 
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleOwner" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.wbkj.pinche-jfO0VlMAhLOI21EuBaSiGA==/base.apk"],nativeLibraryDirectories=[/data/app/com.wbkj.pinche-jfO0VlMAhLOI21EuBaSiGA==/lib/arm, /system/fake-libs, /data/app/com.wbkj.pinche-jfO0VlMAhLOI21EuBaSiGA==/base.apk!/lib/armeabi, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:171)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:36) 
        at com.yanzhenjie.album.api.choice.ImageChoice.multipleChoice(ImageChoice.java:26) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.addPic(ProductImgAddActivity.java:190) 
        at com.wbkj.pinche.activity.ProductImgAddActivity.onViewClicked(ProductImgAddActivity.java:179) 
        at com.wbkj.pinche.activity.ProductImgAddActivity_ViewBinding$2.doClick(ProductImgAddActivity_ViewBinding.java:48) 
        at butterknife.internal.DebouncingOnClickListener.onClick(DebouncingOnClickListener.java:22) 
        at android.view.View.performClick(View.java:6614) 
        at android.view.View.performClickInternal(View.java:6591) 
        at android.view.View.access$3100(View.java:786) 
        at android.view.View$PerformClick.run(View.java:25948) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:207) 
        at android.app.ActivityThread.main(ActivityThread.java:6809) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:876) 
    java.lang.ClassNotFoundException: com.yanzhenjie.album.app.Contract$AlbumPresenter
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    	at com.yanz

**Comment by prakashmp** [comment]
@liujiwei5018 am getting same issue ..could you please suggest the solution .

**Comment by prakashmp** [comment]
any update ? regrading this issue ???
