### ISSUE TITLE
选择图片，对图片进行缩放时，会出现异常

### ISSUE THREAD

**Issue by liufei96** [yanzhenjie/Album#275]
java.lang.IllegalArgumentException: pointerIndex out of range
	at android.view.MotionEvent.nativeGetAxisValue(Native Method)
	at android.view.MotionEvent.getX(MotionEvent.java:1979)
	at android.support.v4.view.ViewPager.onInterceptTouchEvent(ViewPager.java:2066)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1859)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at android.view.ViewGroup.dispatchTransformedTouchEvent(ViewGroup.java:2218)
	at android.view.ViewGroup.dispatchTouchEvent(ViewGroup.java:1959)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.superDispatchTouchEvent(PhoneWindow.java:2125)
	at com.android.internal.policy.impl.PhoneWindow.superDispatchTouchEvent(PhoneWindow.java:1572)
	at android.app.Activity.dispatchTouchEvent(Activity.java:2510)
	at android.support.v7.view.WindowCallbackWrapper.dispatchTouchEvent(WindowCallbackWrapper.java:68)
	at com.android.internal.policy.impl.PhoneWindow$DecorView.dispatchTouchEvent(PhoneWindow.java:2073)
	at android.view.View.dispatchPointerEvent(View.java:7919)
	at android.view.ViewRootImpl$ViewPostImeInputStage.processPointerEvent(ViewRootImpl.java:4235)
	at android.view.ViewRootImpl$ViewPostImeInputStage.onProcess(ViewRootImpl.java:4114)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3663)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3632)
	at android.view.ViewRootImpl$AsyncInputStage.forward(ViewRootImpl.java:3739)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3640)
	at android.view.ViewRootImpl$AsyncInputStage.apply(ViewRootImpl.java:3796)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
	at android.view.ViewRootImpl$InputStage.onDeliverToNext(ViewRootImpl.java:3663)
	at android.view.ViewRootImpl$InputStage.forward(ViewRootImpl.java:3632)
	at android.view.ViewRootImpl$InputStage.apply(ViewRootImpl.java:3640)
	at android.view.ViewRootImpl$InputStage.deliver(ViewRootImpl.java:3613)
	at android.view.ViewRootImpl.deliverInputEvent(ViewRootImpl.java:5883)
	at android.view.ViewRootImpl.doProcessInputEvents(ViewRootImpl.java:5863)
	at android.view.ViewRootImpl.enqueueInputEvent(ViewRootImpl.java:5834)
	at android.view.ViewRootImpl$WindowInputEventReceiver.onInputEvent(ViewRootImpl.java:5974)
	at android.view.InputEventReceiver.dispatchInputEvent(InputEventReceiver.java:185)
	at android.view.InputEventReceiver.nativeConsumeBatchedInputEvents(Native Method)
	at android.view.InputEventReceiver.consumeBatchedInputEvents(InputEventReceiver.java:176)
	at android.view.ViewRootImpl.doConsumeBatchedInput(ViewRootImpl.java:5936)
	at android.view.ViewRootImpl$ConsumeBatchedInputRunnable.run(ViewRootImpl.java:5997)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:787)
	at android.view.Choreographer.doCallbacks(Choreographer.java:600)
	at android.view.Choreographer.doFrame(Choreographer.java:567)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:773)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5291)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:849)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:665)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by github-of-daibing** [comment]
我也遇到了这个问题

**Comment by Hertz52** [comment]
@liufei96 @github-of-daibing 
试下```PhotoViewAttacher.setAllowParentInterceptOnEdge(false);```

        /**
         * Here we decide whether to let the ImageView's parent to start taking
         * over the touch event.
         *
         * First we check whether this function is enabled. We never want the
         * parent to take over if we're scaling. We then check the edge we're
         * on, and the direction of the scroll (i.e. if we're pulling against
         * the edge, aka 'overscrolling', let the parent take over).
         */
