### ISSUE TITLE
                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/app/Contract$AlbumPresenter;

### ISSUE THREAD

**Issue by prakashmp** [yanzhenjie/Album#296]
> `FATAL EXCEPTION: main
                                                               Process: com.upliftapp, PID: 32587
                                                               java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/app/Contract$AlbumPresenter;
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:36)
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:26)
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.selectAlbum(AlbumActivity.java:83)
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.onOptionsItemSelected(AlbumActivity.java:160)
                                                                   at android.app.Activity.onMenuItemSelected(Activity.java:3630)
                                                                   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361)
                                                                   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195)
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108)
                                                                   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65)
                                                                   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202)
                                                                   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780)
                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822)
                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171)
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973)
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963)
                                                                   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624)
                                                                   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150)
                                                                   at android.view.View.performClick(View.java:7339)
                                                                   at android.widget.TextView.performClick(TextView.java:14222)
                                                                   at android.view.View.performClickInternal(View.java:7305)
                                                                   at android.view.View.access$3200(View.java:846)
                                                                   at android.view.View$PerformClick.run(View.java:27787)
                                                                   at android.os.Handler.handleCallback(Handler.java:873)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:214)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7078)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
                                                                Caused by: java.lang.ClassNotFoundException: com.yanzhenjie.album.app.Contract$AlbumPresenter
                                                                   at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                   at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:36) 
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:26) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.selectAlbum(AlbumActivity.java:83) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.onOptionsItemSelected(AlbumActivity.java:160) 
                                                                   at android.app.Activity.onMenuItemSelected(Activity.java:3630) 
                                                                   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361) 
                                                                   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65) 
                                                                   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202) 
                                                                   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780) 
                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822) 
                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963) 
                                                                   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624) 
                                                                   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150) 
                                                                   at android.view.View.performClick(View.java:7339) 
                                                                   at android.widget.TextView.performClick(TextView.java:14222) 
                                                                   at android.view.View.performClickInternal(View.java:7305) 
                                                                   at android.view.View.access$3200(View.java:846) 
                                                                   at android.view.View$PerformClick.run(View.java:27787) 
                                                                   at android.os.Handler.handleCallback(Handler.java:873) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:214) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7078) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
                                                                Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/yanzhenjie/album/mvp/BasePresenter;
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:36) 
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:26) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.selectAlbum(AlbumActivity.java:83) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.onOptionsItemSelected(AlbumActivity.java:160) 
                                                                   at android.app.Activity.onMenuItemSelected(Activity.java:3630) 
                                                                   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361) 
                                                                   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65) 
                                                                   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202) 
                                                                   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780) 
                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822) 
                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963) 
                                                                   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624) 
                                                                   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150) 
                                                                   at android.view.View.performClick(View.java:7339) 
                                                                   at android.widget.TextView.performClick(TextView.java:14222) 
                                                                   at android.view.View.performClickInternal(View.java:7305) 
                                                                   at android.view.View.access$3200(View.java:846) 
                                                                   at android.view.View$PerformClick.run(View.java:27787) 
                                                                   at android.os.Handler.handleCallback(Handler.java:873) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:214) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7078) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
                                                                Caused by: java.lang.ClassNotFoundException: com.yanzhenjie.album.mvp.BasePresenter
                                                                   at java.lang.VMClassLoader.findLoadedClass(Native Method)
                                                                   at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:36) 
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:26) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.selectAlbum(AlbumActivity.java:83) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.onOptionsItemSelected(AlbumActivity.java:160) 
                                                                   at android.app.Activity.onMenuItemSelected(Activity.java:3630) 
                                                                   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361) 
                                                                   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65) 
                                                                   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202) 
                                                                   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780) 
                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822) 
                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963) 
                                                                   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624) 
                                                                   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150) 
                                                                   at android.view.View.performClick(View.java:7339) 
                                                                   at android.widget.TextView.performClick(TextView.java:14222) 
                                                                   at android.view.View.performClickInternal(View.java:7305) 
                                                                   at android.view.View.access$3200(View.java:846) 
                                                                   at android.view.View$PerformClick.run(View.java:27787) 
                                                                   at android.os.Handler.handleCallback(Handler.java:873) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:214) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7078) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
                                                                Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleOwner;
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:36) 
                                                                   at com.yanzhenjie.album.api.choice.AlbumChoice.multipleChoice(AlbumChoice.java:26) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.selectAlbum(AlbumActivity.java:83) 
                                                                   at com.upliftapp.add_mint_showroom.Custom_camera_gallery.app.AlbumActivity.onOptionsItemSelected(AlbumActivity.java:160) 
                                                                   at android.app.Activity.onMenuItemSelected(Activity.java:3630) 
                                                                   at android.support.v4.app.FragmentActivity.onMenuItemSelected(FragmentActivity.java:361) 
                                                                   at android.support.v7.app.AppCompatActivity.onMenuItemSelected(AppCompatActivity.java:195) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.view.WindowCallbackWrapper.onMenuItemSelected(WindowCallbackWrapper.java:108) 
                                                                   at android.support.v7.app.ToolbarActionBar$2.onMenuItemClick(ToolbarActionBar.java:65) 
                                                                   at android.support.v7.widget.Toolbar$1.onMenuItemClick(Toolbar.java:202) 
                                                                   at android.support.v7.widget.ActionMenuView$MenuBuilderCallback.onMenuItemSelected(ActionMenuView.java:780) 
                                                                   at android.support.v7.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:822) 
                                                                   at android.support.v7.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:171) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:973) 
                                                                   at android.support.v7.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:963) 
                                                                   at android.support.v7.widget.ActionMenuView.invokeItem(ActionMenuView.java:624) 
                                                                   at android.support.v7.view.menu.ActionMenuItemView.onClick(ActionMenuItemView.java:150) 
                                                                   at android.view.View.performClick(View.java:7339) 
                                                                   at android.widget.TextView.performClick(TextView.java:14222) 
                                                                   at android.view.View.performClickInternal(View.java:7305) 
                                                                   at android.view.View.access$3200(View.java:846) 
                                                                   at android.view.View$PerformClick.run(View.java:27787) 
                                                                   at android.os.Handler.handleCallback(Handler.java:873) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:214) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:7078) 
                                                                   at java.lang.reflect.Method.invoke(Native Method) 
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:494) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964) 
02-03 18:30:59.184 32587-32587/com.upliftapp E/AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleOwner" on path: DexPathList[[zip file "/system/framework/com.google.android.maps.jar", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/base.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_dependencies_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_0_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_1_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_2_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_3_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_4_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_5_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_6_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_7_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_8_apk.apk", zip file "/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_9_apk.apk"],nativeLibraryDirectories=[/data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/lib/arm64, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/base.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_dependencies_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_0_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_1_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_2_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_3_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_4_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_5_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_6_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_7_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_8_apk.apk!/lib/arm64-v8a, /data/app/com.upliftapp-3qtjnHhkTMN6VfUn04sVlQ==/split_lib_slice_9_apk.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64]]
                                                                   at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                   at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                   	... 30 more`

**Comment by prakashmp** [comment]
Any update ? @yanzhenjie @carvaldo @fiona0419 @mansya
