### ISSUE TITLE
关于在android7.0中路径配置的问题

### ISSUE THREAD

**Issue by xintanggithub** [yanzhenjie/Album#37]
在android 7.0 中。

E/StrictMode: null
                                                                          java.lang.Throwable: file:///storage/emulated/0/DCIM/20170510_111203602.jpg exposed beyond app through ClipData.Item.getUri()
                                                                              at android.os.StrictMode.onFileUriExposed(StrictMode.java:1818)
                                                                              at android.net.Uri.checkFileUriExposed(Uri.java:2350)
                                                                              at android.content.ClipData.prepareToLeaveProcess(ClipData.java:832)
                                                                              at android.content.Intent.prepareToLeaveProcess(Intent.java:9052)
                                                                              at android.content.Intent.prepareToLeaveProcess(Intent.java:9037)
                                                                              at android.app.Instrumentation.execStartActivity(Instrumentation.java:1530)
                                                                              at android.app.Activity.startActivityForResult(Activity.java:4391)
                                                                              at android.support.v4.app.BaseFragmentActivityJB.startActivityForResult(BaseFragmentActivityJB.java:50)
                                                                              at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:79)
                                                                              at android.app.Activity.startActivityForResult(Activity.java:4335)
                                                                              at android.support.v4.app.FragmentActivity.startActivityForResult(FragmentActivity.java:859)
                                                                              at com.yanzhenjie.album.util.AlbumUtils.startCamera(AlbumUtils.java:37)
                                                                              at com.yanzhenjie.album.AlbumActivity.startCamera(AlbumActivity.java:222)
                                                                              at com.yanzhenjie.album.AlbumActivity.access$700(AlbumActivity.java:63)
                                                                              at com.yanzhenjie.album.AlbumActivity$3.onClick(AlbumActivity.java:204)
                                                                              at com.yanzhenjie.album.adapter.AlbumContentAdapter$GalleryContentButtonHolder.onClick(AlbumContentAdapter.java:200)
                                                                              at android.view.View.performClick(View.java:5646)
                                                                              at android.view.View$PerformClick.run(View.java:22459)
                                                                              at android.os.Handler.handleCallback(Handler.java:761)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:98)
                                                                              at android.os.Looper.loop(Looper.java:156)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6523)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)
请问有暴露路径设置的方法吗？ 单独给定FileProvider感觉不太好用

**Comment by yanzhenjie** [comment]
你用的是哪个版本？相机功能兼容7.0并可以指定拍照的路径，请看下ReadMe。

**Comment by xintanggithub** [comment]
感谢，之前是使用的album方法，流程界面和需求很符合。经过你提醒才发现camere下有imagePath配置。
