### ISSUE TITLE
权限问题

### ISSUE THREAD

**Issue by sungentim** [yanzhenjie/Album#39]
版本：1.0.5
phone：RedMi 3s  6.0.1
targetSdk:21

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:309)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=8025, uid=10126 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:493)
	at android.content.ContentResolver.query(ContentResolver.java:435)
	at android.provider.MediaStore$Images$Media.query(MediaStore.java:841)
	at com.yanzhenjie.album.task.ScanTask.getPhotoAlbum(ScanTask.java:112)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:88)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.SecurityException: Permission Denial: reading com.android.providers.media.MediaProvider uri content://media/external/images/media from pid=8025, uid=10126 requires android.permission.READ_EXTERNAL_STORAGE, or grantUriPermission()
	at android.os.Parcel.readException(Parcel.java:1620)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
	at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
	at android.content.ContentProviderProxy.query(ContentProviderNative.java:421)
	at android.content.ContentResolver.query(ContentResolver.java:493)
	at android.content.ContentResolver.query(ContentResolver.java:435)
	at android.provider.MediaStore$Images$Media.query(MediaStore.java:841)
	at com.yanzhenjie.album.task.ScanTask.getPhotoAlbum(ScanTask.java:112)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:88)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by yanzhenjie** [comment]
是demo出现的还是你的app出现的？你是不是没有在manifest.xml中声明ReadMe中提到的三个权限？
