### ISSUE TITLE
java.lang.RuntimeException: The scanner is running

### ISSUE THREAD

**Issue by sungentim** [yanzhenjie/Album#40]
版本：1.0.5
phone:多款手机
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=196908, result=-1, data=null} to activity {com.woodpecker.master/com.yanzhenjie.album.AlbumActivity}: java.lang.RuntimeException: The scanner is running.
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3423)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3466)
	at android.app.ActivityThread.access$1300(ActivityThread.java:142)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5241)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)
Caused by: java.lang.RuntimeException: The scanner is running.
	at com.yanzhenjie.mediascanner.MediaScanner.scan(MediaScanner.java:89)
	at com.yanzhenjie.mediascanner.MediaScanner.scan(MediaScanner.java:71)
	at com.yanzhenjie.album.fragment.AlbumFragment.onCameraBack(AlbumFragment.java:273)
	at com.yanzhenjie.album.fragment.BasicCameraFragment.onActivityResult(BasicCameraFragment.java:137)
	at com.yanzhenjie.album.fragment.AlbumFragment.onActivityResult(AlbumFragment.java:63)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:5458)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3419)
	... 11 more
java.lang.RuntimeException: The scanner is running.
	at com.yanzhenjie.mediascanner.MediaScanner.scan(MediaScanner.java:89)
	at com.yanzhenjie.mediascanner.MediaScanner.scan(MediaScanner.java:71)
	at com.yanzhenjie.album.fragment.AlbumFragment.onCameraBack(AlbumFragment.java:273)
	at com.yanzhenjie.album.fragment.BasicCameraFragment.onActivityResult(BasicCameraFragment.java:137)
	at com.yanzhenjie.album.fragment.AlbumFragment.onActivityResult(AlbumFragment.java:63)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:5458)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3419)
	at android.app.ActivityThread.handleSendResult(ActivityThread.java:3466)
	at android.app.ActivityThread.access$1300(ActivityThread.java:142)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1261)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:136)
	at android.app.ActivityThread.main(ActivityThread.java:5241)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:515)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
	at dalvik.system.NativeStart.main(Native Method)

**Comment by yanzhenjie** [comment]
升级到最新版即解决。
