### ISSUE TITLE
Caused by: java.lang.NullPointerException

### ISSUE THREAD

**Issue by sungentim** [yanzhenjie/Album#41]
版本：1.0.5
phone：HM 2A
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:304)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:235)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
	at com.yanzhenjie.album.task.ScanTask.getPhotoAlbum(ScanTask.java:121)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:88)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
java.lang.NullPointerException
	at com.yanzhenjie.album.task.ScanTask.getPhotoAlbum(ScanTask.java:121)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:88)
	at com.yanzhenjie.album.task.ScanTask.doInBackground(ScanTask.java:38)
	at android.os.AsyncTask$2.call(AsyncTask.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:235)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by yanzhenjie** [comment]
你发布这个issue的时候1.0.6已经发布几天了，是否使用过新版尝试呢？
