### ISSUE TITLE
在模拟器运行，提示Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider

### ISSUE THREAD

**Issue by wangshanhai** [yanzhenjie/Album#45]
在模拟器运行，提示Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider

以下是报错信息，在真机运行就可以，模拟器一运行，打开就崩溃，不知道这个问题有谁遇到过？求回复
 java.lang.RuntimeException: Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.album.provider.CameraFileProvider" on path: /data/app/com.htjy.university-1.apk
                                                     at android.app.ActivityThread.installProvider(ActivityThread.java:4822)
                                                     at android.app.ActivityThread.installContentProviders(ActivityThread.java:4432)
                                                     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4372)
                                                     at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
                                                     at android.os.Handler.dispatchMessage(Handler.java:99)
                                                     at android.os.Looper.loop(Looper.java:137)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                     at java.lang.reflect.Method.invokeNative(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:511)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                     at dalvik.system.NativeStart.main(Native Method)

**Comment by jeonhei** [comment]
确实会如此 这个比较痛苦 望作者修复

**Comment by yanzhenjie** [comment]
@jeonhei 说的挺有道理的，我会在内部尝试修复一下，以免开发者犯这个错误。

**Comment by tangchao0106** [comment]
MyApplication extends MultiDexApplication 就可以了
