### ISSUE TITLE
荣耀NEM-TL00H选择拍完照的照片时崩溃,非必现

### ISSUE THREAD

**Issue by yaojunyi3721** [yanzhenjie/Album#48]
系统Android6.0 未root
起初用的album1.0 发现问题后改用1.0.6问题依旧
使用1.0的方式调用相册
```
Album.startAlbum(mContext, mRequestCode
                            , num                                                         // 指定选择数量。
                            , ContextCompat.getColor(mContext, R.color.colorPrimary)        // 指定Toolbar的颜色。
                            , ContextCompat.getColor(mContext, R.color.colorPrimaryDark));  // 指定状态栏的颜色。
```
日志
```
java.lang.RuntimeException: Unable to resume activity {hf.lskj.com.hplk/com.yanzhenjie.album.AlbumActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131372, result=-1, data=null} to activity {hf.lskj.com.hplk/com.yanzhenjie.album.AlbumActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3176)
	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3207)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2544)
	at android.app.ActivityThread.access$900(ActivityThread.java:168)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1378)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:822)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=131372, result=-1, data=null} to activity {hf.lskj.com.hplk/com.yanzhenjie.album.AlbumActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3778)
	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3163)
	... 10 more
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'char[] java.lang.String.toCharArray()' on a null object reference
	at java.io.File.fixSlashes(File.java:183)
	at java.io.File.<init>(File.java:130)
	at com.yanzhenjie.album.fragment.AlbumFragment.onCameraBack(AlbumFragment.java:275)
	at com.yanzhenjie.album.fragment.BasicCameraFragment.onActivityResult(BasicCameraFragment.java:137)
	at com.yanzhenjie.album.fragment.AlbumFragment.onActivityResult(AlbumFragment.java:63)
	at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
	at android.app.Activity.dispatchActivityResult(Activity.java:6602)
	at android.app.ActivityThread.deliverResults(ActivityThread.java:3774)
```

**Comment by yanzhenjie** [comment]
昨晚发布了新版本1.0.7，尝试修复了这个问题，你可以使用新版试试看。
