### ISSUE TITLE
金立F103 相册版本1.0.3  拍照后点击确定出现崩溃 

### ISSUE THREAD

**Issue by niehaonan** [yanzhenjie/Album#52]
Process: com.zchl, PID: 11824
                                                          java.lang.RuntimeException: Unable to resume activity {com.zchl/com.yanzhenjie.album.AlbumActivity}: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3141)
                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3172)
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2527)
                                                              at android.app.ActivityThread.access$800(ActivityThread.java:167)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417)
                                                              at android.os.Handler.dispatchMessage(Handler.java:111)
                                                              at android.os.Looper.loop(Looper.java:179)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5537)
                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:372)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)
                                                           Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.List.get(int)' on a null object reference
                                                              at com.yanzhenjie.album.fragment.AlbumFragment.showImageFromFolder(AlbumFragment.java:205)
                                                              at com.yanzhenjie.album.fragment.AlbumFragment.onResume(AlbumFragment.java:161)
                                                              at android.support.v4.app.Fragment.performResume(Fragment.java:2238)
                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1346)
                                                              at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
                                                              at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
                                                              at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2914)
                                                              at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
                                                              at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:509)
                                                              at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:498)
                                                              at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
                                                              at android.app.Activity.performResume(Activity.java:6074)
                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3126)
                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3172) 
                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2527) 
                                                              at android.app.ActivityThread.access$800(ActivityThread.java:167) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1417) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:111) 
                                                              at android.os.Looper.loop(Looper.java:179) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5537) 
                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                              at java.lang.reflect.Method.invoke(Method.java:372) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:956) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:751)

**Comment by yanzhenjie** [comment]
1.0.3呀，现在都1.0.6了，你升级一下，应该早就没问题了，等下我要发布1.0.7了，不过是无缝升级的，你先用1.0.6解决问题，大家都在用。

**Comment by yanzhenjie** [comment]
昨晚发布了新版，1.0.7，尝试修复了这个问题，你可以再试试看。
