### ISSUE TITLE
4.4 Android 系统不支持

### ISSUE THREAD

**Issue by HelloLollipop** [yanzhenjie/Album#54]
如图，出现classnotfoundexception闪退

**Comment by yanzhenjie** [comment]
没有看到你所说的图，另外请贴出堆栈信息，否则没法准确的帮你解决问题。
Android4.4 我们实测后是没有问题的，很多时候`ClassNotFoundException`可能是方法数超过65535了，AS会自动做multiDex支持，但仅限于 Android5.0 及以后的系统，5.0以下请参考[利用android-support-multidex解决65536问题64k问题](http://blog.csdn.net/yanzhenjie1003/article/details/51818269)。

**Comment by HelloLollipop** [comment]
抱歉，信息不全，请稍等

**Comment by HelloLollipop** [comment]
4.4多个不同品牌的rom下出现
Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider
且application没有启动时就闪退

**Comment by yanzhenjie** [comment]
#45

**Comment by HelloLollipop** [comment]
直接升级1.0.7，rebuild可否？

**Comment by HelloLollipop** [comment]
刚升级，在测试中~

**Comment by HelloLollipop** [comment]
还是崩溃，并且崩溃日志也看不到，application都没有进入

**Comment by HelloLollipop** [comment]
java.lang.RuntimeException: Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.album.provider.CameraFileProvider" on path: DexPathList[[zip file "/data/app/com.isolarcloud.manager-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.isolarcloud.manager-1, /system/lib]]
                                                                           at android.app.ActivityThread.installProvider(ActivityThread.java:4793)

Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.album.provider.CameraFileProvider" on path: DexPathList[[zip file "/data/app/com.isolarcloud.manager-1.apk"],nativeLibraryDirectories=[/data/app-lib/com.isolarcloud.manager-1, /system/lib]]
                                                                           at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)

已升级1.0.7还是出现这个问题

**Comment by yanzhenjie** [comment]
上面的第一回复和第二个回复中的引用有看吗？

**Comment by HelloLollipop** [comment]
方法数么有超过65536啊
我从来都不用instant run的
库已经升级到1.0.7了
混淆文件中已经保留了alunm的类...
测试环境原生4.4

**Comment by HelloLollipop** [comment]
靠- -解决了，继承的Application换成MultiDexApplication自动解决了...
