### ISSUE TITLE
拍照时抛出的异常

### ISSUE THREAD

**Issue by artshell** [yanzhenjie/Album#72]
```java
FATAL EXCEPTION: main
                                                               java.lang.RuntimeException: Unable to resume activity {com.stuliving/com.yanzhenjie.album.AlbumActivity}: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65836, result=-1, data=null} to activity {com.stuliving/com.yanzhenjie.album.AlbumActivity}: java.lang.NullPointerException
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2828)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2857)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2287)
                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:147)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                   at android.os.Looper.loop(Looper.java:137)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5265)
                                                                   at java.lang.reflect.Method.invokeNative(Native Method)
                                                                   at java.lang.reflect.Method.invoke(Method.java:525)
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576)
                                                                   at dalvik.system.NativeStart.main(Native Method)
                                                                Caused by: java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=65836, result=-1, data=null} to activity {com.stuliving/com.yanzhenjie.album.AlbumActivity}: java.lang.NullPointerException
                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:3421)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2815)
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2857) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2287) 
                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:147) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5265) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
                                                                Caused by: java.lang.NullPointerException
                                                                   at com.yanzhenjie.album.fragment.AlbumFragment.onCameraBack(AlbumFragment.java:289)
                                                                   at com.yanzhenjie.album.fragment.BasicCameraFragment.onActivityResult(BasicCameraFragment.java:145)
                                                                   at com.yanzhenjie.album.fragment.AlbumFragment.onActivityResult(AlbumFragment.java:62)
                                                                   at android.support.v4.app.FragmentActivity.onActivityResult(FragmentActivity.java:164)
                                                                   at android.app.Activity.dispatchActivityResult(Activity.java:5335)
                                                                   at android.app.ActivityThread.deliverResults(ActivityThread.java:3417)
                                                                   at android.app.ActivityThread.performResumeActivity(ActivityThread.java:2815) 
                                                                   at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:2857) 
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2287) 
                                                                   at android.app.ActivityThread.access$600(ActivityThread.java:147) 
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1272) 
                                                                   at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                   at android.os.Looper.loop(Looper.java:137) 
                                                                   at android.app.ActivityThread.main(ActivityThread.java:5265) 
                                                                   at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                   at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:760) 
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:576) 
                                                                   at dalvik.system.NativeStart.main(Native Method) 
```

**Comment by yanzhenjie** [comment]
刚刚发布了2.0-alpha版本，我们公司已经在使用了，2.0变化比较大，你可以试试2.0。

**Comment by artshell** [comment]
@yanzhenjie 谢谢啊
