### ISSUE TITLE
在一个Activity中点击第二次就会报错

### ISSUE THREAD

**Issue by ziabo** [yanzhenjie/Album#73]
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.util.Locale.equals(java.lang.Object)' on a null object reference
                                                                                 at android.app.ActivityThread.updateLocaleListFromAppContext(ActivityThread.java:5095)
                                                                                 at android.app.ActivityThread.handleConfigurationChanged(ActivityThread.java:4777)
                                                                                 at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2736)
                                                                                 at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1493)
                                                                                 at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                                 at android.app.ActivityThread.main(ActivityThread.java:6195)
                                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:874)
                                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:764)

**Comment by yanzhenjie** [comment]
昨天下午发布了新版，新版修复了这个问题，新版以流式Api的形式提供开发者调用，比较友好。对于旧版，你可以在初始化的时候设置Locale就不会出现这个问题了。
