### ISSUE TITLE
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yanzhenjie.album.api.widget.Widget.getNavigationBarColor()' on a null object reference

### ISSUE THREAD

**Issue by coolspan** [yanzhenjie/Album#83]
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.fotoable.free.music/com.yanzhenjie.album.ui.AlbumActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yanzhenjie.album.api.widget.Widget.getNavigationBarColor()' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2724)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:208)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'int com.yanzhenjie.album.api.widget.Widget.getNavigationBarColor()' on a null object reference
       at com.yanzhenjie.album.ui.AlbumActivity.initializeWidget(AlbumActivity.java:101)
       at com.yanzhenjie.album.ui.AlbumActivity.onCreate(AlbumActivity.java:77)
       at android.app.Activity.performCreate(Activity.java:6701)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1118)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2677)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2789)
       at android.app.ActivityThread.-wrap12(ActivityThread.java)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1527)
       at android.os.Handler.dispatchMessage(Handler.java:110)
       at android.os.Looper.loop(Looper.java:208)
       at android.app.ActivityThread.main(ActivityThread.java:6267)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)

**Comment by yanzhenjie** [comment]
请参考：#100 。
