### ISSUE TITLE
Caused by java.lang.NullPointerException        at com.yanzhenjie.album.ui.AlbumActivity.initializeWidget(AlbumActivity.java:101)

### ISSUE THREAD

**Issue by coolspan** [yanzhenjie/Album#85]
`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.xxxxx/com.yanzhenjie.album.ui.AlbumActivity}: java.lang.NullPointerException
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2429)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)
Caused by java.lang.NullPointerException
       at com.yanzhenjie.album.ui.AlbumActivity.initializeWidget(AlbumActivity.java:101)
       at com.yanzhenjie.album.ui.AlbumActivity.onCreate(AlbumActivity.java:77)
       at android.app.Activity.performCreate(Activity.java:5442)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1094)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2393)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2493)
       at android.app.ActivityThread.access$800(ActivityThread.java:166)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1283)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5584)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1268)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1084)
       at dalvik.system.NativeStart.main(NativeStart.java)`

**Comment by yanzhenjie** [comment]
不好意思，最近一直忙所以没来Github看issue。  
请描述一下上面的异常出现的场景：  
1. 一打开就报错了。
2. 打开Album长期至于后台通过任务列表再次打开后出现。

或者是其它场景麻烦描述一下，方便我排查bug。

**Comment by yanzhenjie** [comment]
请参考：#100。

**Comment by yanzhenjie** [comment]
根据[#100-342698524](https://github.com/yanzhenjie/Album/issues/100#issuecomment-342698524)的测试，应该不是NoFragment的混淆问题，具体可能还是上面说的被系统回收或者开发者设置了null Widget的原因，还请回复一下。

**Comment by coolspan** [comment]
可能是由于内存泄漏导致的，之前传的上下文是Activity，后来我改为Application了，但是还会存在空指针问题，谢谢

**Comment by yanzhenjie** [comment]
你是哪个版本，看代码这里是不应该出现空指针的。
```text
dalvik.system.NativeStart.main(NativeStart.java) Caused by java.lang.NullPointerException
com.yanzhenjie.album.ui.AlbumActivity.initializeWidget(AlbumActivity.java:101)
com.yanzhenjie.album.ui.AlbumActivity.onCreate(AlbumActivity.java:77)
```
如果是旧版本的话你换一下新版本试试看。

**Comment by coolspan** [comment]
2.0.1最新版本，我是从fabric上看到的，崩溃几十次吧，我没复现出来，我是为了这个库更加稳定所以才反馈的，概率很小，可以关闭问题的

**Comment by yanzhenjie** [comment]
非常感谢反馈，不过不知道复现场景，我再尝试着做做容错。
