### ISSUE TITLE
4.4.4 报如下错误  怎么解决

### ISSUE THREAD

**Issue by wlingf** [yanzhenjie/Album#94]
java.lang.RuntimeException: Unable to get provider com.yanzhenjie.album.provider.CameraFileProvider: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.album.provider.CameraFileProvider" on path: DexPathList[[zip file "/data/app/com.shengyun.pay-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.shengyun.pay-2, /system/lib]]
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4777)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369)
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309)
                      at android.app.ActivityThread.access$1500(ActivityThread.java:135)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:136)
                      at android.app.ActivityThread.main(ActivityThread.java:5001)
                      at java.lang.reflect.Method.invokeNative(Native Method)
                      at java.lang.reflect.Method.invoke(Method.java:515)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
                      at dalvik.system.NativeStart.main(Native Method)
                   Caused by: java.lang.ClassNotFoundException: Didn't find class "com.yanzhenjie.album.provider.CameraFileProvider" on path: DexPathList[[zip file "/data/app/com.shengyun.pay-2.apk"],nativeLibraryDirectories=[/data/app-lib/com.shengyun.pay-2, /system/lib]]
                      at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:497)
                      at java.lang.ClassLoader.loadClass(ClassLoader.java:457)
                      at android.app.ActivityThread.installProvider(ActivityThread.java:4762)
                      at android.app.ActivityThread.installContentProviders(ActivityThread.java:4369) 
                      at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4309) 
                      at android.app.ActivityThread.access$1500(ActivityThread.java:135) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256) 
                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                      at android.os.Looper.loop(Looper.java:136) 
                      at android.app.ActivityThread.main(ActivityThread.java:5001) 
                      at java.lang.reflect.Method.invokeNative(Native Method) 
                      at java.lang.reflect.Method.invoke(Method.java:515) 
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601) 
                      at dalvik.system.NativeStart.main(Native Method)

**Comment by yanzhenjie** [comment]
方法数达到64k容易出现`ClassNotFoundException`和`NotClassDefFoundError`的错误，你可以按照这篇文章的教程来处理一下：  
[AndroidStudio利用android-support-multidex解决65536问题64k问题](http://blog.csdn.net/yanzhenjie1003/article/details/51818269)
